Features/#214 landuse areas
openego/eGon-data pull request #219
Opened 2021-04-19 13:03 UTC by IlkaCu

Fixes #214

2021-04-21 06:16 UTC, gplssm requested changes
Please see the one comment in a changed file.

You could consider to add a bit more documentation in the SQL code. Just consider the case someone else would have to change anything ;-)
Maybe I'm a bit picky about this after reviewing and partially reimplementing old open_ego code about MV grid districts...

Apart from that, I must say that I get an error which I don't understand:
```
[2021-04-21 08:12:23,940] {logging_mixin.py:112} INFO - Running <TaskInstance: egon-data-processing-pipeline.extract-osm_landuse 2021-04-21T06:03:44.339975+00:00 [running]> on host RLI-NB-49
[2021-04-21 08:12:23,964] {postgres_operator.py:62} INFO - Executing: /*
OSM landuse sectors
Extract landuse areas from OpenStreetMap.
Cut the landuse with German boders (vg250) and make valid geometries.
Divide into 4 landuse sectors:
1. Residential
2. Retail
3. Industrial
4. Agricultural
__copyright__   = "Reiner Lemoine Institut"
__license__     = "GNU Affero General Public License Version 3 (AGPL-3.0)"
__url__         = "https://github.com/openego/data_processing/blob/master/LICENSE"
__author__      = "Ludee, IlkaCu"
*/


---------- ---------- ----------
-- Filter OSM Urban Landuse
---------- ---------- ----------

DELETE FROM openstreetmap.osm_polygon_urban; 

-- filter urban

INSERT INTO            openstreetmap.osm_polygon_urban
    SELECT  osm.gid ::integer AS gid,
            osm.osm_id ::integer AS osm_id,
            --osm.landuse ::text AS landuse,
            --osm.man_made ::text AS man_made,
            --osm.aeroway ::text AS aeroway,
            osm.name ::text AS name,
            --osm.way_area ::double precision AS way_area,
            '0' ::integer AS sector,
            'undefined'::text AS sector_name, 
            ST_AREA(ST_TRANSFORM(osm.geom,3035))/10000 ::double precision AS area_ha,
            osm.tags ::hstore AS tags,
            'outside' ::text AS vg250,
            ST_MULTI(ST_TRANSFORM(osm.geom,3035)) ::geometry(MultiPolygon,3035) AS geom
    FROM    openstreetmap.osm_polygon AS osm
    WHERE
        tags @> '"landuse"=>"residential"'::hstore OR 
        tags @> '"landuse"=>"commercial"'::hstore OR 
        tags @> '"landuse"=>"retail"'::hstore OR 
        tags @> '"landuse"=>"industrial;retail"'::hstore OR 

        tags @> '"landuse"=>"industrial"'::hstore OR 
        tags @> '"landuse"=>"port"'::hstore OR 
        tags @> '"man_made"=>"wastewater_plant"'::hstore OR
        tags @> '"aeroway"=>"terminal"'::hstore OR 
        tags @> '"aeroway"=>"gate"'::hstore OR 
        tags @> '"man_made"=>"works"'::hstore OR 

        tags @> '"landuse"=>"farmyard"'::hstore OR 
        tags @> '"landuse"=>"greenhouse_horticulture"'::hstore 
    ORDER BY    osm.gid;


-- OSM Urban Landuse Inside vg250

-- Calculate 'inside' vg250
UPDATE 	openstreetmap.osm_polygon_urban AS t1
	SET  	vg250 = t2.vg250
	FROM    (
		SELECT	osm.gid AS gid,
			'inside' ::text AS vg250
		FROM	boundaries.vg250_sta_union AS vg,
			openstreetmap.osm_polygon_urban AS osm
		WHERE  	vg.geometry && osm.geom AND
			ST_CONTAINS(vg.geometry,osm.geom)
		) AS t2
	WHERE  	t1.gid = t2.gid;

-- Calculate 'crossing' vg250
UPDATE 	openstreetmap.osm_polygon_urban AS t1
	SET  	vg250 = t2.vg250
	FROM    (
		SELECT	osm.gid AS gid,
			'crossing' ::text AS vg250
		FROM	boundaries.vg250_sta_union AS vg,
			openstreetmap.osm_polygon_urban AS osm
		WHERE  	osm.vg250 = 'outside' AND
			vg.geometry && osm.geom AND
			ST_Overlaps(vg.geometry,osm.geom)
		) AS t2
	WHERE  	t1.gid = t2.gid;


-- OSM outside of vg250

-- OSM error vg250
DROP MATERIALIZED VIEW IF EXISTS	openstreetmap.osm_polygon_urban_error_geom_vg250 CASCADE;
CREATE MATERIALIZED VIEW		openstreetmap.osm_polygon_urban_error_geom_vg250 AS
	SELECT	osm.*
	FROM	openstreetmap.osm_polygon_urban AS osm
	WHERE	osm.vg250 = 'outside' OR osm.vg250 = 'crossing';

-- index (id)
CREATE UNIQUE INDEX  	osm_polygon_urban_error_geom_vg250_gid_idx
		ON	openstreetmap.osm_polygon_urban_error_geom_vg250 (gid);

-- index GIST (geom)
CREATE INDEX  	osm_polygon_urban_error_geom_vg250_geom_idx
	ON	openstreetmap.osm_polygon_urban_error_geom_vg250
	USING	GIST (geom);

-- Sequence
DROP SEQUENCE IF EXISTS 	openstreetmap.osm_polygon_urban_vg250_cut_id CASCADE;
CREATE SEQUENCE 		openstreetmap.osm_polygon_urban_vg250_cut_id;

-- Cutting 'crossing' with vg250
DROP MATERIALIZED VIEW IF EXISTS	openstreetmap.osm_polygon_urban_vg250_cut;
CREATE MATERIALIZED VIEW		openstreetmap.osm_polygon_urban_vg250_cut AS
	SELECT	nextval('openstreetmap.osm_polygon_urban_vg250_cut_id') ::integer AS id,
		cut.gid ::integer AS gid,
		cut.osm_id ::integer AS osm_id,
		--cut.landuse ::text AS landuse,
		--cut.man_made ::text AS man_made,
		--cut.aeroway ::text AS aeroway,
		cut.name ::text AS name,
		--cut.way_area ::double precision AS way_area,
		cut.sector ::integer AS sector,
		cut.sector_name::text AS sector_name,
		cut.area_ha ::double precision AS area_ha,
		cut.tags ::hstore AS tags,
		cut.vg250 ::text AS vg250,
		GeometryType(cut.geom_new) ::text AS geom_type,
		ST_MULTI(ST_TRANSFORM(cut.geom_new,3035)) ::geometry(MultiPolygon,3035) AS geom
	FROM	(SELECT	poly.*,
			ST_INTERSECTION(poly.geom, cut.geometry) AS geom_new
		FROM	openstreetmap.osm_polygon_urban_error_geom_vg250 AS poly,
			boundaries.vg250_sta_union AS cut
		WHERE	poly.vg250 = 'crossing'
		) AS cut
	ORDER BY 	cut.gid;

-- index (id)
CREATE UNIQUE INDEX  	osm_polygon_urban_vg250_cut_gid_idx
		ON	openstreetmap.osm_polygon_urban_vg250_cut (gid);

-- index GIST (geom)
CREATE INDEX  	osm_polygon_urban_vg250_cut_geom_idx
	ON	openstreetmap.osm_polygon_urban_vg250_cut
	USING	GIST (geom);

-- 'crossing' Polygon to MultiPolygon
DROP MATERIALIZED VIEW IF EXISTS	openstreetmap.osm_polygon_urban_vg250_clean_cut_multi;
CREATE MATERIALIZED VIEW		openstreetmap.osm_polygon_urban_vg250_clean_cut_multi AS
	SELECT	nextval('openstreetmap.osm_polygon_gid_seq'::regclass) ::integer AS gid,
		cut.osm_id ::integer AS osm_id,
		--cut.landuse ::text AS landuse,
		--cut.man_made ::text AS man_made,
		--cut.aeroway ::text AS aeroway,
		cut.name ::text AS name,
		cut.sector ::integer AS sector,
		cut.sector_name::text AS sector_name,
		--cut.way_area ::double precision AS way_area,
		cut.area_ha ::double precision AS area_ha,
		cut.tags ::hstore AS tags,
		cut.vg250 ::text AS vg250,
		ST_MULTI(cut.geom) ::geometry(MultiPolygon,3035) AS geom
	FROM	openstreetmap.osm_polygon_urban_vg250_cut AS cut
	WHERE	cut.geom_type = 'POLYGON';

-- index (id)
CREATE UNIQUE INDEX  	osm_polygon_urban_vg250_clean_cut_multi_gid_idx
		ON	openstreetmap.osm_polygon_urban_vg250_clean_cut_multi (gid);

-- index GIST (geom)
CREATE INDEX  	osm_polygon_urban_vg250_clean_cut_multi_geom_idx
	ON	openstreetmap.osm_polygon_urban_vg250_clean_cut_multi
	USING	GIST (geom);

---------- ---------- ----------

-- clean cut
DROP MATERIALIZED VIEW IF EXISTS	openstreetmap.osm_polygon_urban_vg250_clean_cut;
CREATE MATERIALIZED VIEW		openstreetmap.osm_polygon_urban_vg250_clean_cut AS
	SELECT	nextval('openstreetmap.osm_polygon_gid_seq'::regclass) ::integer AS gid,
		cut.osm_id ::integer AS osm_id,
		--cut.landuse ::text AS landuse,
		--cut.man_made ::text AS man_made,
		--cut.aeroway ::text AS aeroway,
		cut.name ::text AS name,
		cut.sector ::integer AS sector,
		cut.sector_name::text AS sector_name, 
		--cut.way_area ::double precision AS way_area,
		cut.area_ha ::double precision AS area_ha,
		cut.tags ::hstore AS tags,
		cut.vg250 ::text AS vg250,
		cut.geom ::geometry(MultiPolygon,3035) AS geom
	FROM	openstreetmap.osm_polygon_urban_vg250_cut AS cut
	WHERE	cut.geom_type = 'MULTIPOLYGON';

-- index (id)
CREATE UNIQUE INDEX  	osm_polygon_urban_vg250_clean_cut_gid_idx
		ON	openstreetmap.osm_polygon_urban_vg250_clean_cut (gid);


-- remove 'outside' vg250
DELETE FROM	openstreetmap.osm_polygon_urban AS osm
	WHERE	osm.vg250 = 'outside';

-- remove 'outside' vg250
DELETE FROM	openstreetmap.osm_polygon_urban AS osm
	WHERE	osm.vg250 = 'crossing';

-- insert cut
INSERT INTO	openstreetmap.osm_polygon_urban
	SELECT	clean.* [...]

2021-04-22 17:20 UTC, IlkaCu commented on src/egon/data/processing/loadarea/osm_landuse_extraction.sql
> +            osm.osm_id ::integer AS osm_id,
Done!

2021-04-22 17:33 UTC, IlkaCu commented
I replaced the btree indexing by a GiST index. I hope this solves the problem for you. 

I also tried to extend the SQL documentation at least a little bit and removed commented parts of the code.

2021-04-26 10:50 UTC, gplssm commented on src/egon/data/processing/loadarea/osm_landuse_extraction.sql
> +            osm.osm_id ::integer AS osm_id,
:+1:

2021-04-26 12:58 UTC, gplssm commented
Thanks for the changes! I was able to execute it and took a look on the data. Seems to be quite decent coverage!

One minor thing I would like to change: renaming the resulting table from osm_polygon_urban to either landuse or landuse_polygons. This table name would tell a bit more what's inside the data.

2021-04-26 12:58 UTC, gplssm approved these changes

2021-04-28 12:41 UTC, merged